
git:
  quiet: true

language: rust

cache:
  cargo

rust:
  - 1.36.0
  - stable

matrix:
  include:
    - os: linux
    - os: osx

script:
  - cargo build
  - cargo test
  - cargo build --feature="extern_crate_alloc"
  - cargo test --feature="extern_crate_alloc"
