
git:
  quiet: true

language: rust

cache:
  cargo

rust:
  - 1.36.0
  - stable

matrix:
  include:
    - { os: osx, rust: 1.36.0 }
    - { os: linux, rust: 1.36.0 }
    - { os: linux, rust: stable }
    - { os: linux, rust: nightly }

script:
  - cargo build
  - cargo test
  - cargo build --features="extern_crate_alloc"
  - cargo test --features="extern_crate_alloc"
