[package]
name = "tinyvec"
description = "Just, really the littlest Vec you could need. So smol."
version = "0.3.0-alpha.0"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib"
keywords = ["vec", "no_std", "no-std", "smol"]
categories = ["data-structures", "no-std"]
repository = "https://github.com/Lokathor/tinyvec"

[dependencies]
# not even std!

[features]
default = []

# Provide things that utilize the `alloc` crate.
alloc = []

# allow use of nightly feature `slice_partition_dedup`,
# will become useless once that is stabilized:
# https://github.com/rust-lang/rust/issues/54279
nightly_slice_partition_dedup = []

# use const generics for arrays
nightly_const_generics = []

[badges]
appveyor = { repository = "Lokathor/tinyvec" }
travis-ci = { repository = "Lokathor/tinyvec" }

[package.metadata.docs.rs]
all-features = true

[workspace]
members = ["fuzz"]

[[test]]
name = "tinyvec"
required-features = ["alloc"]
