[package]
name = "tinyvec"
description = "Just, really the littlest Vec you could need. So smol."
version = "0.0.1-alpha.0"
authors = ["Lokathor <zefria@gmail.com>"]
#edition = "2018" # until our min version is allowed to go up, 2015 it is.
license = "Zlib"
keywords = ["vec", "no_std", "smol"]
categories = ["data-structures", "no-std"]

[dependencies]
# not even std!

[features]
default = []
rustc_28 = []

[badges]
appveyor = { repository = "Lokathor/tinyvec" }
travis-ci = { repository = "Lokathor/tinyvec" }
