name: Rust

on: [push]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
        - 1.34.0
        - stable
        - beta
        - nightly
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
    - name: Test The Basics Everywhere
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Test Stable and Later Features
      if: matrix.rust != '1.34.0'
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features=alloc --features=grab_spare_slice --features=rustc_1_40
    - name: Test Nightly Features
      if: matrix.rust == 'nightly'
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
